In [5]:
import numpy as np

In [7]:
lst = [1, 2, 3, 4, 5]
arr = np.array(lst)

In [13]:
arr

array([1, 2, 3, 4, 5])

In [8]:
type(arr)

numpy.ndarray

In [12]:
print(arr)

[1 2 3 4 5]


To demonstrate 2 dimentionals array

In [73]:
row1 = [1, 2, 3, 4, 5, 6, 0, 8]
row2 = [1, 2, 3, 4, 5, 6, 7, 8]
row3 = [1, 2, 3, 4, 5, 6, 7, 8]
row4 = [1, 2, 3, 4, 5, 6, 7, 8]
row5 = [1, 2, 3, 4, 5, 6, 7, 8]
row6 = [1, 2, 3, 4, 5, 6, 7, 8]
row7 = [1, 2, 3, 4, 5, 6, 7, 8]
row8 = [1, 2, 3, 4, 5, 6, 7, 8]

board = np.array([row1, row2, row3, row4, row5, row6, row7, row8])
type(board)
#board.reshape(16, 4)
#board.fill(0)

board[4, 4] = 90
board[:, :]

array([[ 1,  2,  3,  4,  5,  6,  0,  8],
       [ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 1,  2,  3,  4, 90,  6,  7,  8],
       [ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 1,  2,  3,  4,  5,  6,  7,  8]])

In [72]:
arr1 = np.arange(1, 700, 10)
arr1[1:5] = 0
arr1

array([  1,   0,   0,   0,   0,  51,  61,  71,  81,  91, 101, 111, 121,
       131, 141, 151, 161, 171, 181, 191, 201, 211, 221, 231, 241, 251,
       261, 271, 281, 291, 301, 311, 321, 331, 341, 351, 361, 371, 381,
       391, 401, 411, 421, 431, 441, 451, 461, 471, 481, 491, 501, 511,
       521, 531, 541, 551, 561, 571, 581, 591, 601, 611, 621, 631, 641,
       651, 661, 671, 681, 691])

In [74]:
arr2 = np.linspace(1, 10, 100)
arr2

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [82]:
board > 2
board[board > 6]

array([ 8,  7,  8,  7,  8,  7,  8, 90,  7,  8,  7,  8,  7,  8,  7,  8])

In [85]:
arr3 = np.ones((8, 8), dtype=int)
arr3

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [88]:
arr4 = np.random.randn(5, 5)
arr4

array([[-1.35590185,  1.56055429, -0.56655047,  1.57209062,  0.0379012 ],
       [ 1.13529347,  1.34700313, -0.81342811, -0.77600075,  1.0969516 ],
       [ 0.18608706, -0.75562104, -0.06612153, -0.2694017 , -1.14920578],
       [ 1.8626201 , -0.33688722,  1.48312396, -0.13444142,  0.21797866],
       [ 0.57005651, -0.21574219,  1.49594281,  0.32594148, -0.08618671]])